new changes from PLP v2
adobe/storefront-product-listing-page pull request #27
Opened 2024-07-30 16:45 UTC by NadiyaS

## Description

This PR contain the latest changes of PLP, which were released in [version 2](https://plp-widgets-ui.magento-ds.com/v2/search.js) for LS 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-07-31 14:21 UTC, benjaminkalk commented on dev-template.html
> +      environmentId: 'cf1d5897-72e8-471a-8c2f-2bed259de3ff',
Should we putting an environment Id into public repo?

2024-07-31 14:22 UTC, benjaminkalk commented on dev-template.html
> +        customerGroup: 'b6589fc6ab0dc82cf12099d1c2d40ab994e8410c',
Same question regarding if we should be including these keys in public repo.

2024-07-31 14:23 UTC, benjaminkalk commented on dev-template.html
> +      storeViewName: 'plp widget',
Same comment as above.  Should we be adding environmentIds

2024-07-31 14:25 UTC, benjaminkalk commented on src/context/store.tsx
> +      //This is for the publix repo setup
Should we keep this comment?

2024-07-31 14:28 UTC, benjaminkalk requested changes
I think we should remove any environment Ids, keys, or config we don't want to expose in public repo.

2024-08-01 13:48 UTC, benjaminkalk approved these changes

2024-08-08 15:23 UTC, grahamcrackers requested changes
Summary:
- Storybook isn't working. I tried to run it locally and styles were broken.
- `npm run lint` exposes 23 warnings which need to be fixed
- We shouldn't be tying our Sentry and Floodgate to an open source repo. Not that it exposes anything critical, but that it will most likely cause issues if a client is forking this repo and customizing things on their end.

2024-08-08 15:23 UTC, grahamcrackers commented on src/index.tsx
> +    <SentryProvider>
We should remove Sentry and probably Floodgate as well.

2024-08-08 15:23 UTC, grahamcrackers commented on src/context/sentry.tsx
> +/*
i'm not sure if we want to expose this publicly

2024-08-08 15:23 UTC, grahamcrackers commented on src/components/WishlistButton/WishlistButton.stories.mdx
> +import { Canvas, Meta, Story, ArgsTable } from '@storybook/addon-docs';
you are adding a .mdx file for storybook, but removing the "mdx" option in the [storybook config](https://github.com/adobe/storefront-product-listing-page/pull/27/files#diff-54238bc08b5014b3bff3682beb27adb9a1463aa0e299333a2abc50909189d9d8R6)?

2024-08-16 14:14 UTC, NadiyaS commented
Changed will be delivered in https://github.com/adobe/storefront-product-listing-page/pull/30

2024-08-16 14:14 UTC, closed without merging